# Generated by Django 5.1.4 on 2024-12-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_flower'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('start_work_time', models.TimeField(default='09:00', verbose_name='Начало рабочего времени')),
                ('end_work_time', models.TimeField(default='18:00', verbose_name='Конец рабочего времени')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
