# Generated by Django 5.1.4 on 2024-12-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bouquet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('in_progress', 'В процессе'), ('delivered', 'Доставлено')], default='pending', max_length=50),
        ),
    ]
