# Generated by Django 5.1.4 on 2024-12-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
