# Generated by Django 5.1.4 on 2024-12-25 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flowers',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.flower')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_app.order')),
            ],
        ),
    ]
